"""Dify-side collaborator for the intent-executor workflow node.

The invoker owns every piece of external I/O the node needs — model schema
inspection, tool runtime construction, the blocking function-calling model
call, and tool execution — so the node itself stays testable with a stub.
"""

from __future__ import annotations

from collections.abc import Generator, Mapping, Sequence
from dataclasses import dataclass, field
from typing import Any

from sqlalchemy import select
from sqlalchemy.orm import Session

from core.agent.entities import AgentToolEntity
from core.app.entities.app_invoke_entities import DifyRunContext
from core.app.file_access import DatabaseFileAccessController
from core.callback_handler.workflow_tool_callback_handler import DifyWorkflowCallbackHandler
from core.db.session_factory import session_factory
from core.model_context import use_credit_usage_metadata
from core.model_manager import ModelInstance
from core.tools.__base.tool import Tool
from core.tools.entities.tool_entities import ToolInvokeMessage, ToolParameter
from core.tools.tool_engine import ToolEngine
from core.tools.tool_manager import ToolManager
from core.tools.utils.message_transformer import ToolFileMessageTransformer
from core.workflow.nodes.agent.entities import ParamsAutoGenerated
from extensions.ext_database import db
from factories import file_factory
from graphon.file import File, FileTransferMethod, get_file_type_by_mime_type
from graphon.model_runtime.entities.llm_entities import LLMResult
from graphon.model_runtime.entities.message_entities import (
    PromptMessage,
    PromptMessageTool,
    SystemPromptMessage,
    UserPromptMessage,
)
from graphon.model_runtime.entities.model_entities import ModelFeature
from graphon.runtime.variable_pool import VariablePool
from models import ToolFile

from .entities import IntentExecutorToolConfig

_file_access_controller = DatabaseFileAccessController()


@dataclass(frozen=True)
class PreparedTool:
    name: str  # tool_name, used as function name
    provider_name: str
    prompt_tool: PromptMessageTool
    tool: Tool


@dataclass(frozen=True)
class IntentToolOutput:
    text: str  # concatenated TEXT/LINK messages
    json: list[dict[str, Any] | list[Any]] = field(default_factory=list)
    files: list[File] = field(default_factory=list)


class IntentExecutorInvoker:
    def __init__(
        self,
        *,
        run_context: DifyRunContext,
        model_instance: ModelInstance,
        request_metadata: Mapping[str, object],
        model_parameters: Mapping[str, Any] | None = None,
        stop: Sequence[str] | None = None,
    ) -> None:
        self._run_context = run_context
        self._model_instance = model_instance
        self._request_metadata = request_metadata
        self._model_parameters = model_parameters or {}
        self._stop = stop

    def supports_tool_call(self) -> bool:
        model_schema = self._model_instance.get_model_schema()
        features = model_schema.features if model_schema is not None else None
        if not features:
            return False
        return ModelFeature.TOOL_CALL in features or ModelFeature.MULTI_TOOL_CALL in features

    def prepare_tools(
        self,
        *,
        tools: Sequence[IntentExecutorToolConfig],
        variable_pool: VariablePool,
    ) -> list[PreparedTool]:
        prepared_tools: list[PreparedTool] = []
        for config in tools:
            if not config.enabled:
                continue

            parameters = self._resolve_tool_parameters(config, variable_pool)
            settings = {key: value.get("value", None) for key, value in config.settings.items()}
            manual_input_params = [key for key, value in parameters.items() if value is not None]
            parameters = {**parameters, **settings}

            entity = AgentToolEntity(
                provider_id=config.provider_name,
                provider_type=config.type,
                tool_name=config.tool_name,
                tool_parameters=parameters,
                plugin_unique_identifier=config.plugin_unique_identifier,
                credential_id=config.credential_id,
            )
            tool_runtime = ToolManager.get_agent_tool_runtime(
                self._run_context.tenant_id,
                self._run_context.app_id,
                entity,
                self._run_context.user_id,
                self._run_context.invoke_from,
                variable_pool,
            )
            if tool_runtime.entity.description:
                tool_runtime.entity.description.llm = (
                    config.extra.get("description", "") or tool_runtime.entity.description.llm
                )
            for tool_runtime_param in tool_runtime.entity.parameters:
                tool_runtime_param.form = (
                    ToolParameter.ToolParameterForm.FORM
                    if tool_runtime_param.name in manual_input_params
                    else tool_runtime_param.form
                )
            if tool_runtime.runtime is not None and tool_runtime.runtime.runtime_parameters is not None:
                manual_input_value = {key: value for key, value in parameters.items() if key in manual_input_params}
                tool_runtime.runtime.runtime_parameters.update(manual_input_value)

            prompt_tool = PromptMessageTool(
                name=config.tool_name,
                description=tool_runtime.entity.description.llm if tool_runtime.entity.description else "",
                parameters=tool_runtime.get_llm_parameters_json_schema(),
            )
            prepared_tools.append(
                PreparedTool(
                    name=config.tool_name,
                    provider_name=config.provider_name,
                    prompt_tool=prompt_tool,
                    tool=tool_runtime,
                )
            )
        return prepared_tools

    def plan(
        self,
        *,
        instruction: str,
        intent: str,
        tools: Sequence[PromptMessageTool],
    ) -> LLMResult:
        prompt_messages: list[PromptMessage] = []
        if instruction:
            prompt_messages.append(SystemPromptMessage(content=instruction))
        prompt_messages.append(UserPromptMessage(content=intent))
        return self._model_instance.invoke_llm(
            prompt_messages=prompt_messages,
            model_parameters=dict(self._model_parameters),
            tools=list(tools),
            stop=list(self._stop) if self._stop else None,
            stream=False,
            request_metadata=self._request_metadata,
        )

    def invoke_tool(
        self,
        *,
        tool: PreparedTool,
        arguments: Mapping[str, Any],
        workflow_call_depth: int,
        conversation_id: str | None,
    ) -> IntentToolOutput:
        request_metadata = {"app_type": self._run_context.app_type} if self._run_context.app_type is not None else None
        with use_credit_usage_metadata(request_metadata):
            session_maker = session_factory.get_session_maker()
            with session_maker.begin() as session:
                messages = ToolEngine.generic_invoke(
                    session=session,
                    tool=tool.tool.fork_tool_runtime(runtime=tool.tool.runtime),
                    tool_parameters=dict(arguments),
                    user_id=self._run_context.user_id,
                    workflow_tool_callback=DifyWorkflowCallbackHandler(),
                    workflow_call_depth=workflow_call_depth,
                    app_id=self._run_context.app_id,
                    conversation_id=conversation_id,
                )
                transformed_messages = ToolFileMessageTransformer.transform_tool_invoke_messages(
                    messages=messages,
                    user_id=self._run_context.user_id,
                    tenant_id=self._run_context.tenant_id,
                    conversation_id=conversation_id,
                )
                return self._collect_output(transformed_messages)

    def _collect_output(
        self,
        messages: Generator[ToolInvokeMessage, None, None],
    ) -> IntentToolOutput:
        text_parts: list[str] = []
        json_list: list[dict[str, Any] | list[Any]] = []
        files: list[File] = []
        for message in messages:
            match message.type:
                case ToolInvokeMessage.MessageType.TEXT | ToolInvokeMessage.MessageType.LINK:
                    if isinstance(message.message, ToolInvokeMessage.TextMessage):
                        text_parts.append(message.message.text)
                case ToolInvokeMessage.MessageType.JSON:
                    if isinstance(message.message, ToolInvokeMessage.JsonMessage):
                        json_list.append(message.message.json_object)
                case ToolInvokeMessage.MessageType.IMAGE_LINK | ToolInvokeMessage.MessageType.BINARY_LINK:
                    files.append(self._file_from_link_message(message))
                case ToolInvokeMessage.MessageType.FILE:
                    meta = message.meta or {}
                    file_value = meta.get("file")
                    if isinstance(file_value, File):
                        files.append(file_value)
                case _:
                    continue
        return IntentToolOutput(text="".join(text_parts), json=json_list, files=files)

    def _file_from_link_message(self, message: ToolInvokeMessage) -> File:
        if not isinstance(message.message, ToolInvokeMessage.TextMessage):
            raise ValueError("file link message is missing text payload")
        meta = message.meta if isinstance(message.meta, Mapping) else {}
        file_value = meta.get("file")
        if isinstance(file_value, File):
            return file_value
        if isinstance(file_value, Mapping):
            return file_factory.build_from_mapping(
                mapping=dict(file_value),
                tenant_id=self._run_context.tenant_id,
                access_controller=_file_access_controller,
            )
        tool_file_id = meta.get("tool_file_id")
        if not isinstance(tool_file_id, str) or not tool_file_id:
            raise ValueError("missing tool_file_id metadata")
        with Session(db.engine) as session:
            tool_file = session.scalar(
                select(ToolFile).where(ToolFile.id == tool_file_id, ToolFile.tenant_id == self._run_context.tenant_id)
            )
            if tool_file is None:
                raise ValueError(f"tool file not found: {tool_file_id}")
        return file_factory.build_from_mapping(
            mapping={
                "tool_file_id": tool_file_id,
                "type": get_file_type_by_mime_type(tool_file.mimetype),
                "transfer_method": meta.get("transfer_method", FileTransferMethod.TOOL_FILE),
                "url": message.message.text,
            },
            tenant_id=self._run_context.tenant_id,
            access_controller=_file_access_controller,
        )

    @staticmethod
    def _resolve_tool_parameters(
        config: IntentExecutorToolConfig,
        variable_pool: VariablePool,
    ) -> dict[str, Any]:
        """Mirror the Agent v1 ``array[tools]`` parameter handling: each entry is
        either ``auto`` (passed through as ``None``), a variable selector, or a
        constant value."""
        parameters = dict(config.parameters)
        if not parameters or not all(isinstance(v, dict) for v in parameters.values()):
            return parameters

        resolved: dict[str, Any] = {}
        for key, param in parameters.items():
            if param.get("auto", ParamsAutoGenerated.OPEN) in (ParamsAutoGenerated.CLOSE, 0):
                value_param = param.get("value", {})
                if value_param and value_param.get("type", "") == "variable":
                    variable_selector = value_param.get("value")
                    if not variable_selector:
                        raise ValueError("Variable selector is missing for a variable-type parameter.")
                    variable = variable_pool.get(variable_selector)
                    if variable is None:
                        raise ValueError(f"Variable {variable_selector} not found")
                    resolved[key] = variable.value
                else:
                    resolved[key] = value_param.get("value", "") if value_param is not None else None
            else:
                resolved[key] = None
        return resolved
